trigger:
- master

pool:
  vmImage: 'windows-2019'

steps:
- task: DotNetCoreInstaller@0
  displayName: 'Use .NET Core SDK 3.0.100 - preview 6'
  inputs:
    version: '3.0.100-preview6-012264'

- script: dotnet restore

- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    command: build
    projects: '**/*.csproj'

- task: DotNetCoreCLI@2
  displayName: Test
  inputs:
    command: test
    projects: '**/*Tests/*.csproj'